export const countryCodes = [
  { code: "+93", country: "AF", flag: "🇦🇫", name: "Afghanistan", key: "af" },
  { code: "+355", country: "AL", flag: "🇦🇱", name: "Albania", key: "al" },
  { code: "+213", country: "DZ", flag: "🇩🇿", name: "Algeria", key: "dz" },
  { code: "+1", country: "AS", flag: "🇦🇸", name: "American Samoa", key: "as" },
  { code: "+376", country: "AD", flag: "🇦🇩", name: "Andorra", key: "ad" },
  { code: "+244", country: "AO", flag: "🇦🇴", name: "Angola", key: "ao" },
  { code: "+1", country: "AI", flag: "🇦🇮", name: "Anguilla", key: "ai" },
  {
    code: "+1",
    country: "AG",
    flag: "🇦🇬",
    name: "Antigua and Barbuda",
    key: "ag",
  },
  { code: "+54", country: "AR", flag: "🇦🇷", name: "Argentina", key: "ar" },
  { code: "+374", country: "AM", flag: "🇦🇲", name: "Armenia", key: "am" },
  { code: "+297", country: "AW", flag: "🇦🇼", name: "Aruba", key: "aw" },
  { code: "+61", country: "AU", flag: "🇦🇺", name: "Australia", key: "au" },
  { code: "+43", country: "AT", flag: "🇦🇹", name: "Austria", key: "at" },
  { code: "+994", country: "AZ", flag: "🇦🇿", name: "Azerbaijan", key: "az" },
  { code: "+1", country: "BS", flag: "🇧🇸", name: "Bahamas", key: "bs" },
  { code: "+973", country: "BH", flag: "🇧🇭", name: "Bahrain", key: "bh" },
  { code: "+880", country: "BD", flag: "🇧🇩", name: "Bangladesh", key: "bd" },
  { code: "+1", country: "BB", flag: "🇧🇧", name: "Barbados", key: "bb" },
  { code: "+375", country: "BY", flag: "🇧🇾", name: "Belarus", key: "by" },
  { code: "+32", country: "BE", flag: "🇧🇪", name: "Belgium", key: "be" },
  { code: "+501", country: "BZ", flag: "🇧🇿", name: "Belize", key: "bz" },
  { code: "+229", country: "BJ", flag: "🇧🇯", name: "Benin", key: "bj" },
  { code: "+1", country: "BM", flag: "🇧🇲", name: "Bermuda", key: "bm" },
  { code: "+975", country: "BT", flag: "🇧🇹", name: "Bhutan", key: "bt" },
  { code: "+591", country: "BO", flag: "🇧🇴", name: "Bolivia", key: "bo" },
  {
    code: "+387",
    country: "BA",
    flag: "🇧🇦",
    name: "Bosnia and Herzegovina",
    key: "ba",
  },
  { code: "+267", country: "BW", flag: "🇧🇼", name: "Botswana", key: "bw" },
  { code: "+55", country: "BR", flag: "🇧🇷", name: "Brazil", key: "br" },
  {
    code: "+1",
    country: "VG",
    flag: "🇻🇬",
    name: "British Virgin Islands",
    key: "vg",
  },
  { code: "+673", country: "BN", flag: "🇧🇳", name: "Brunei", key: "bn" },
  { code: "+359", country: "BG", flag: "🇧🇬", name: "Bulgaria", key: "bg" },
  { code: "+226", country: "BF", flag: "🇧🇫", name: "Burkina Faso", key: "bf" },
  { code: "+257", country: "BI", flag: "🇧🇮", name: "Burundi", key: "bi" },
  { code: "+855", country: "KH", flag: "🇰🇭", name: "Cambodia", key: "kh" },
  { code: "+237", country: "CM", flag: "🇨🇲", name: "Cameroon", key: "cm" },
  { code: "+1", country: "CA", flag: "🇨🇦", name: "Canada", key: "ca" },
  { code: "+238", country: "CV", flag: "🇨🇻", name: "Cape Verde", key: "cv" },
  { code: "+1", country: "KY", flag: "🇰🇾", name: "Cayman Islands", key: "ky" },
  {
    code: "+236",
    country: "CF",
    flag: "🇨🇫",
    name: "Central African Republic",
    key: "cf",
  },
  { code: "+235", country: "TD", flag: "🇹🇩", name: "Chad", key: "td" },
  { code: "+56", country: "CL", flag: "🇨🇱", name: "Chile", key: "cl" },
  { code: "+86", country: "CN", flag: "🇨🇳", name: "China", key: "cn" },
  { code: "+57", country: "CO", flag: "🇨🇴", name: "Colombia", key: "co" },
  { code: "+269", country: "KM", flag: "🇰🇲", name: "Comoros", key: "km" },
  { code: "+242", country: "CG", flag: "🇨🇬", name: "Congo", key: "cg" },
  { code: "+243", country: "CD", flag: "🇨🇩", name: "Congo (DRC)", key: "cd" },
  { code: "+682", country: "CK", flag: "🇨🇰", name: "Cook Islands", key: "ck" },
  { code: "+506", country: "CR", flag: "🇨🇷", name: "Costa Rica", key: "cr" },
  { code: "+225", country: "CI", flag: "🇨🇮", name: "Côte d'Ivoire", key: "ci" },
  { code: "+385", country: "HR", flag: "🇭🇷", name: "Croatia", key: "hr" },
  { code: "+53", country: "CU", flag: "🇨🇺", name: "Cuba", key: "cu" },
  { code: "+357", country: "CY", flag: "🇨🇾", name: "Cyprus", key: "cy" },
  {
    code: "+420",
    country: "CZ",
    flag: "🇨🇿",
    name: "Czech Republic",
    key: "cz",
  },
  { code: "+45", country: "DK", flag: "🇩🇰", name: "Denmark", key: "dk" },
  { code: "+253", country: "DJ", flag: "🇩🇯", name: "Djibouti", key: "dj" },
  { code: "+1", country: "DM", flag: "🇩🇲", name: "Dominica", key: "dm" },
  {
    code: "+1",
    country: "DO",
    flag: "🇩🇴",
    name: "Dominican Republic",
    key: "do",
  },
  { code: "+593", country: "EC", flag: "🇪🇨", name: "Ecuador", key: "ec" },
  { code: "+20", country: "EG", flag: "🇪🇬", name: "Egypt", key: "eg" },
  { code: "+503", country: "SV", flag: "🇸🇻", name: "El Salvador", key: "sv" },
  {
    code: "+240",
    country: "GQ",
    flag: "🇬🇶",
    name: "Equatorial Guinea",
    key: "gq",
  },
  { code: "+291", country: "ER", flag: "🇪🇷", name: "Eritrea", key: "er" },
  { code: "+372", country: "EE", flag: "🇪🇪", name: "Estonia", key: "ee" },
  { code: "+251", country: "ET", flag: "🇪🇹", name: "Ethiopia", key: "et" },
  {
    code: "+500",
    country: "FK",
    flag: "🇫🇰",
    name: "Falkland Islands",
    key: "fk",
  },
  { code: "+298", country: "FO", flag: "🇫🇴", name: "Faroe Islands", key: "fo" },
  { code: "+679", country: "FJ", flag: "🇫🇯", name: "Fiji", key: "fj" },
  { code: "+358", country: "FI", flag: "🇫🇮", name: "Finland", key: "fi" },
  { code: "+33", country: "FR", flag: "🇫🇷", name: "France", key: "fr" },
  { code: "+594", country: "GF", flag: "🇬🇫", name: "French Guiana", key: "gf" },
  {
    code: "+689",
    country: "PF",
    flag: "🇵🇫",
    name: "French Polynesia",
    key: "pf",
  },
  { code: "+241", country: "GA", flag: "🇬🇦", name: "Gabon", key: "ga" },
  { code: "+220", country: "GM", flag: "🇬🇲", name: "Gambia", key: "gm" },
  { code: "+995", country: "GE", flag: "🇬🇪", name: "Georgia", key: "ge" },
  { code: "+49", country: "DE", flag: "🇩🇪", name: "Germany", key: "de" },
  { code: "+233", country: "GH", flag: "🇬🇭", name: "Ghana", key: "gh" },
  { code: "+350", country: "GI", flag: "🇬🇮", name: "Gibraltar", key: "gi" },
  { code: "+30", country: "GR", flag: "🇬🇷", name: "Greece", key: "gr" },
  { code: "+299", country: "GL", flag: "🇬🇱", name: "Greenland", key: "gl" },
  { code: "+1", country: "GD", flag: "🇬🇩", name: "Grenada", key: "gd" },
  { code: "+590", country: "GP", flag: "🇬🇵", name: "Guadeloupe", key: "gp" },
  { code: "+1", country: "GU", flag: "🇬🇺", name: "Guam", key: "gu" },
  { code: "+502", country: "GT", flag: "🇬🇹", name: "Guatemala", key: "gt" },
  { code: "+224", country: "GN", flag: "🇬🇳", name: "Guinea", key: "gn" },
  { code: "+245", country: "GW", flag: "🇬🇼", name: "Guinea-Bissau", key: "gw" },
  { code: "+592", country: "GY", flag: "🇬🇾", name: "Guyana", key: "gy" },
  { code: "+509", country: "HT", flag: "🇭🇹", name: "Haiti", key: "ht" },
  { code: "+504", country: "HN", flag: "🇭🇳", name: "Honduras", key: "hn" },
  { code: "+852", country: "HK", flag: "🇭🇰", name: "Hong Kong SAR", key: "hk" },
  { code: "+36", country: "HU", flag: "🇭🇺", name: "Hungary", key: "hu" },
  { code: "+354", country: "IS", flag: "🇮🇸", name: "Iceland", key: "is" },
  { code: "+91", country: "IN", flag: "🇮🇳", name: "India", key: "in" },
  { code: "+62", country: "ID", flag: "🇮🇩", name: "Indonesia", key: "id" },
  { code: "+98", country: "IR", flag: "🇮🇷", name: "Iran", key: "ir" },
  { code: "+964", country: "IQ", flag: "🇮🇶", name: "Iraq", key: "iq" },
  { code: "+353", country: "IE", flag: "🇮🇪", name: "Ireland", key: "ie" },
  { code: "+972", country: "IL", flag: "🇮🇱", name: "Israel", key: "il" },
  { code: "+39", country: "IT", flag: "🇮🇹", name: "Italy", key: "it" },
  { code: "+1", country: "JM", flag: "🇯🇲", name: "Jamaica", key: "jm" },
  { code: "+81", country: "JP", flag: "🇯🇵", name: "Japan", key: "jp" },
  { code: "+962", country: "JO", flag: "🇯🇴", name: "Jordan", key: "jo" },
  { code: "+7", country: "KZ", flag: "🇰🇿", name: "Kazakhstan", key: "kz" },
  { code: "+254", country: "KE", flag: "🇰🇪", name: "Kenya", key: "ke" },
  { code: "+686", country: "KI", flag: "🇰🇮", name: "Kiribati", key: "ki" },
  { code: "+965", country: "KW", flag: "🇰🇼", name: "Kuwait", key: "kw" },
  { code: "+996", country: "KG", flag: "🇰🇬", name: "Kyrgyzstan", key: "kg" },
  { code: "+856", country: "LA", flag: "🇱🇦", name: "Laos", key: "la" },
  { code: "+371", country: "LV", flag: "🇱🇻", name: "Latvia", key: "lv" },
  { code: "+961", country: "LB", flag: "🇱🇧", name: "Lebanon", key: "lb" },
  { code: "+266", country: "LS", flag: "🇱🇸", name: "Lesotho", key: "ls" },
  { code: "+231", country: "LR", flag: "🇱🇷", name: "Liberia", key: "lr" },
  { code: "+218", country: "LY", flag: "🇱🇾", name: "Libya", key: "ly" },
  { code: "+423", country: "LI", flag: "🇱🇮", name: "Liechtenstein", key: "li" },
  { code: "+370", country: "LT", flag: "🇱🇹", name: "Lithuania", key: "lt" },
  { code: "+352", country: "LU", flag: "🇱🇺", name: "Luxembourg", key: "lu" },
  { code: "+853", country: "MO", flag: "🇲🇴", name: "Macao SAR", key: "mo" },
  { code: "+389", country: "MK", flag: "🇲🇰", name: "Macedonia", key: "mk" },
  { code: "+261", country: "MG", flag: "🇲🇬", name: "Madagascar", key: "mg" },
  { code: "+265", country: "MW", flag: "🇲🇼", name: "Malawi", key: "mw" },
  { code: "+60", country: "MY", flag: "🇲🇾", name: "Malaysia", key: "my" },
  { code: "+960", country: "MV", flag: "🇲🇻", name: "Maldives", key: "mv" },
  { code: "+223", country: "ML", flag: "🇲🇱", name: "Mali", key: "ml" },
  { code: "+356", country: "MT", flag: "🇲🇹", name: "Malta", key: "mt" },
  {
    code: "+692",
    country: "MH",
    flag: "🇲🇭",
    name: "Marshall Islands",
    key: "mh",
  },
  { code: "+596", country: "MQ", flag: "🇲🇶", name: "Martinique", key: "mq" },
  { code: "+222", country: "MR", flag: "🇲🇷", name: "Mauritania", key: "mr" },
  { code: "+230", country: "MU", flag: "🇲🇺", name: "Mauritius", key: "mu" },
  { code: "+262", country: "YT", flag: "🇾🇹", name: "Mayotte", key: "yt" },
  { code: "+52", country: "MX", flag: "🇲🇽", name: "Mexico", key: "mx" },
  { code: "+691", country: "FM", flag: "🇫🇲", name: "Micronesia", key: "fm" },
  { code: "+373", country: "MD", flag: "🇲🇩", name: "Moldova", key: "md" },
  { code: "+377", country: "MC", flag: "🇲🇨", name: "Monaco", key: "mc" },
  { code: "+976", country: "MN", flag: "🇲🇳", name: "Mongolia", key: "mn" },
  { code: "+382", country: "ME", flag: "🇲🇪", name: "Montenegro", key: "me" },
  { code: "+1", country: "MS", flag: "🇲🇸", name: "Montserrat", key: "ms" },
  { code: "+212", country: "MA", flag: "🇲🇦", name: "Morocco", key: "ma" },
  { code: "+258", country: "MZ", flag: "🇲🇿", name: "Mozambique", key: "mz" },
  { code: "+95", country: "MM", flag: "🇲🇲", name: "Myanmar", key: "mm" },
  { code: "+264", country: "NA", flag: "🇳🇦", name: "Namibia", key: "na" },
  { code: "+674", country: "NR", flag: "🇳🇷", name: "Nauru", key: "nr" },
  { code: "+977", country: "NP", flag: "🇳🇵", name: "Nepal", key: "np" },
  { code: "+31", country: "NL", flag: "🇳🇱", name: "Netherlands", key: "nl" },
  { code: "+687", country: "NC", flag: "🇳🇨", name: "New Caledonia", key: "nc" },
  { code: "+64", country: "NZ", flag: "🇳🇿", name: "New Zealand", key: "nz" },
  { code: "+505", country: "NI", flag: "🇳🇮", name: "Nicaragua", key: "ni" },
  { code: "+227", country: "NE", flag: "🇳🇪", name: "Niger", key: "ne" },
  { code: "+234", country: "NG", flag: "🇳🇬", name: "Nigeria", key: "ng" },
  { code: "+683", country: "NU", flag: "🇳🇺", name: "Niue", key: "nu" },
  {
    code: "+672",
    country: "NF",
    flag: "🇳🇫",
    name: "Norfolk Island",
    key: "nf",
  },
  { code: "+850", country: "KP", flag: "🇰🇵", name: "North Korea", key: "kp" },
  {
    code: "+1",
    country: "MP",
    flag: "🇲🇵",
    name: "Northern Mariana Islands",
    key: "mp",
  },
  { code: "+47", country: "NO", flag: "🇳🇴", name: "Norway", key: "no" },
  { code: "+968", country: "OM", flag: "🇴🇲", name: "Oman", key: "om" },
  { code: "+92", country: "PK", flag: "🇵🇰", name: "Pakistan", key: "pk" },
  { code: "+680", country: "PW", flag: "🇵🇼", name: "Palau", key: "pw" },
  { code: "+970", country: "PS", flag: "🇵🇸", name: "Palestine", key: "ps" },
  { code: "+507", country: "PA", flag: "🇵🇦", name: "Panama", key: "pa" },
  {
    code: "+675",
    country: "PG",
    flag: "🇵🇬",
    name: "Papua New Guinea",
    key: "pg",
  },
  { code: "+595", country: "PY", flag: "🇵🇾", name: "Paraguay", key: "py" },
  { code: "+51", country: "PE", flag: "🇵🇪", name: "Peru", key: "pe" },
  { code: "+63", country: "PH", flag: "🇵🇭", name: "Philippines", key: "ph" },
  { code: "+48", country: "PL", flag: "🇵🇱", name: "Poland", key: "pl" },
  { code: "+351", country: "PT", flag: "🇵🇹", name: "Portugal", key: "pt" },
  { code: "+1", country: "PR", flag: "🇵🇷", name: "Puerto Rico", key: "pr" },
  { code: "+974", country: "QA", flag: "🇶🇦", name: "Qatar", key: "qa" },
  { code: "+262", country: "RE", flag: "🇷🇪", name: "Réunion", key: "re" },
  { code: "+40", country: "RO", flag: "🇷🇴", name: "Romania", key: "ro" },
  { code: "+7", country: "RU", flag: "🇷🇺", name: "Russia", key: "ru" },
  { code: "+250", country: "RW", flag: "🇷🇼", name: "Rwanda", key: "rw" },
  {
    code: "+590",
    country: "BL",
    flag: "🇧🇱",
    name: "Saint Barthélemy",
    key: "bl",
  },
  { code: "+290", country: "SH", flag: "🇸🇭", name: "Saint Helena", key: "sh" },
  {
    code: "+1",
    country: "KN",
    flag: "🇰🇳",
    name: "Saint Kitts and Nevis",
    key: "kn",
  },
  { code: "+1", country: "LC", flag: "🇱🇨", name: "Saint Lucia", key: "lc" },
  { code: "+590", country: "MF", flag: "🇲🇫", name: "Saint Martin", key: "mf" },
  {
    code: "+508",
    country: "PM",
    flag: "🇵🇲",
    name: "Saint Pierre and Miquelon",
    key: "pm",
  },
  {
    code: "+1",
    country: "VC",
    flag: "🇻🇨",
    name: "Saint Vincent and the Grenadines",
    key: "vc",
  },
  { code: "+685", country: "WS", flag: "🇼🇸", name: "Samoa", key: "ws" },
  { code: "+378", country: "SM", flag: "🇸🇲", name: "San Marino", key: "sm" },
  {
    code: "+239",
    country: "ST",
    flag: "🇸🇹",
    name: "São Tomé and Príncipe",
    key: "st",
  },
  { code: "+966", country: "SA", flag: "🇸🇦", name: "Saudi Arabia", key: "sa" },
  { code: "+221", country: "SN", flag: "🇸🇳", name: "Senegal", key: "sn" },
  { code: "+381", country: "RS", flag: "🇷🇸", name: "Serbia", key: "rs" },
  { code: "+248", country: "SC", flag: "🇸🇨", name: "Seychelles", key: "sc" },
  { code: "+232", country: "SL", flag: "🇸🇱", name: "Sierra Leone", key: "sl" },
  { code: "+65", country: "SG", flag: "🇸🇬", name: "Singapore", key: "sg" },
  { code: "+1", country: "SX", flag: "🇸🇽", name: "Sint Maarten", key: "sx" },
  { code: "+421", country: "SK", flag: "🇸🇰", name: "Slovakia", key: "sk" },
  { code: "+386", country: "SI", flag: "🇸🇮", name: "Slovenia", key: "si" },
  {
    code: "+677",
    country: "SB",
    flag: "🇸🇧",
    name: "Solomon Islands",
    key: "sb",
  },
  { code: "+252", country: "SO", flag: "🇸🇴", name: "Somalia", key: "so" },
  { code: "+27", country: "ZA", flag: "🇿🇦", name: "South Africa", key: "za" },
  { code: "+82", country: "KR", flag: "🇰🇷", name: "South Korea", key: "kr" },
  { code: "+211", country: "SS", flag: "🇸🇸", name: "South Sudan", key: "ss" },
  { code: "+34", country: "ES", flag: "🇪🇸", name: "Spain", key: "es" },
  { code: "+94", country: "LK", flag: "🇱🇰", name: "Sri Lanka", key: "lk" },
  { code: "+249", country: "SD", flag: "🇸🇩", name: "Sudan", key: "sd" },
  { code: "+597", country: "SR", flag: "🇸🇷", name: "Suriname", key: "sr" },
  {
    code: "+47",
    country: "SJ",
    flag: "🇸🇯",
    name: "Svalbard and Jan Mayen",
    key: "sj",
  },
  { code: "+268", country: "SZ", flag: "🇸🇿", name: "Swaziland", key: "sz" },
  { code: "+46", country: "SE", flag: "🇸🇪", name: "Sweden", key: "se" },
  { code: "+41", country: "CH", flag: "🇨🇭", name: "Switzerland", key: "ch" },
  { code: "+963", country: "SY", flag: "🇸🇾", name: "Syria", key: "sy" },
  { code: "+886", country: "TW", flag: "🇹🇼", name: "Taiwan", key: "tw" },
  { code: "+992", country: "TJ", flag: "🇹🇯", name: "Tajikistan", key: "tj" },
  { code: "+255", country: "TZ", flag: "🇹🇿", name: "Tanzania", key: "tz" },
  { code: "+66", country: "TH", flag: "🇹🇭", name: "Thailand", key: "th" },
  { code: "+670", country: "TL", flag: "🇹🇱", name: "Timor-Leste", key: "tl" },
  { code: "+228", country: "TG", flag: "🇹🇬", name: "Togo", key: "tg" },
  { code: "+690", country: "TK", flag: "🇹🇰", name: "Tokelau", key: "tk" },
  { code: "+676", country: "TO", flag: "🇹🇴", name: "Tonga", key: "to" },
  {
    code: "+1",
    country: "TT",
    flag: "🇹🇹",
    name: "Trinidad and Tobago",
    key: "tt",
  },
  { code: "+216", country: "TN", flag: "🇹🇳", name: "Tunisia", key: "tn" },
  { code: "+90", country: "TR", flag: "🇹🇷", name: "Turkey", key: "tr" },
  { code: "+993", country: "TM", flag: "🇹🇲", name: "Turkmenistan", key: "tm" },
  {
    code: "+1",
    country: "TC",
    flag: "🇹🇨",
    name: "Turks and Caicos Islands",
    key: "tc",
  },
  { code: "+688", country: "TV", flag: "🇹🇻", name: "Tuvalu", key: "tv" },
  { code: "+256", country: "UG", flag: "🇺🇬", name: "Uganda", key: "ug" },
  { code: "+380", country: "UA", flag: "🇺🇦", name: "Ukraine", key: "ua" },
  {
    code: "+971",
    country: "AE",
    flag: "🇦🇪",
    name: "United Arab Emirates",
    key: "ae",
  },
  { code: "+44", country: "GB", flag: "🇬🇧", name: "United Kingdom", key: "gb" },
  { code: "+1", country: "US", flag: "🇺🇸", name: "United States", key: "us" },
  { code: "+598", country: "UY", flag: "🇺🇾", name: "Uruguay", key: "uy" },
  {
    code: "+1",
    country: "VI",
    flag: "🇻🇮",
    name: "US Virgin Islands",
    key: "vi",
  },
  { code: "+998", country: "UZ", flag: "🇺🇿", name: "Uzbekistan", key: "uz" },
  { code: "+678", country: "VU", flag: "🇻🇺", name: "Vanuatu", key: "vu" },
  { code: "+379", country: "VA", flag: "🇻🇦", name: "Vatican City", key: "va" },
  { code: "+58", country: "VE", flag: "🇻🇪", name: "Venezuela", key: "ve" },
  { code: "+84", country: "VN", flag: "🇻🇳", name: "Vietnam", key: "vn" },
  {
    code: "+681",
    country: "WF",
    flag: "🇼🇫",
    name: "Wallis and Futuna",
    key: "wf",
  },
  {
    code: "+212",
    country: "EH",
    flag: "🇪🇭",
    name: "Western Sahara",
    key: "eh",
  },
  { code: "+967", country: "YE", flag: "🇾🇪", name: "Yemen", key: "ye" },
  { code: "+260", country: "ZM", flag: "🇿🇲", name: "Zambia", key: "zm" },
  { code: "+263", country: "ZW", flag: "🇿🇼", name: "Zimbabwe", key: "zw" },
];

export type CountryCode = {
  code: string;
  country: string;
  flag: string;
  name: string;
  key: string;
};
